{{- if .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentEnv.labels" . | nindent 4 }}
{{- end }}
